### ISSUE TITLE
Error in computing the loss function

### ISSUE THREAD

**Issue by deeplearn-strasbourg** [zylo117/Yet-Another-EfficientDet-Pytorch#373]
I am training on a custom dataset, 2 classes. After the first epoch, I get the error: 

/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [0,0,0], thread: [0,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [0,0,0], thread: [1,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.

Yet-Another-EfficientDet-Pytorch/efficientdet/loss.py", line 127, in forward
    if positive_indices.sum() > 0:
RuntimeError: CUDA error: device-side assert triggered

I tried without GPU, but I still get an error. Do you have any idea why this happens? Thank you

**Comment by zylo117** [comment]
If you train on cpu, what's the error?
I think it's probably dataset issue. You should compare the shape dataset from the tutorial, which also contains 2 classes, with yours.

**Comment by deeplearn-strasbourg** [comment]
Thank you for your answer!
When I set GPU=0, I get: 
Yet-Another-EfficientDet-Pytorch/efficientdet/loss.py", line 105, in forward
targets[positive_indices, assigned_annotations[positive_indices, 4].long()] = 1
IndexError: index 2 is out of bounds for dimension 1 with size 2

You are right, there must be something with the dataset. The stucture of the dataset is the one you give: datasts/project_name/etc , object_list in yaml has the 2 classes. What else can it be? Thank you

**Comment by zylo117** [comment]
category id starts from 1

**Comment by deeplearn-strasbourg** [comment]
It is working now. Thank you! You pointed in the right direction, the dataset. I have the category id starting from 1, but I had an extra class in the validation set. This is why I could train without the validation set.
